choices_TImputacion = [
        ('Sin Imputacion', '1 - Sin Imputacion'),
        ('Gastos de Explot', '2 - Gastos de Explot'),
        ('Bienes de Uso', '3 - Bienes de Uso'),
        ('Com.y Lubricant.', '4 - Com.y Lubricant.'),
        ('Seguros', '5 - Seguros'),
        ('Alquiler', '6 - Alquiler'),
        ('Peaje', '7 - Peaje'),
        ('Gas Oil', '8 - Gas Oil'),
        ('Vtas.Consu.Final', '9 - Vtas.Consu.Final'),
        ('Vtas.RI.y Ext.', '10 - Vtas.RI.y Ext.'),
        ('Vtas.CF IVA 10,5', '11 - Vtas.CF IVA 10,5'),
        ('Vtas.RI IVA 10,5', '12 - Vtas.RI IVA 10,5'),
        ('Vtas.CF Gomeria', '13 - Vtas.CF Gomeria'),
        ('Vtas.RI Gomeria', '14 - Vtas.RI Gomeria'),
        ('Vtas.CF Lavadero', '15 - Vtas.CF Lavadero'),
        ('Vtas.RI Lavadero', '16 - Vtas.RI Lavadero'),
        ('Vtas.CF Mecanico', '17 - Vtas.CF Mecanico'),
        ('Vtas.RI Mecanico', '18 - Vtas.RI Mecanico'),
        ('Monotributo', '19 - Monotributo'),
        ('Ipt.Deb.Ley25413', '20 - Ipt.Deb.Ley25413'),
        ('Cpras.DGR Bs.As.', '21 - Cpras.DGR Bs.As.'),
        ('Comisiones', '22 - Comisiones'),
        ('Gastos Bancarios', '23 - Gastos Bancarios'),
        ('Vtas.Cielo.R.I.', '24 - Vtas.Cielo.R.I.'),
        ('Vtas.Cielo.C.F.', '25 - Vtas.Cielo.C.F.'),
        ('Ropa de Trabajo', '26 - Ropa de Trabajo'),
        ('Vtas.Chaco', '27 - Vtas.Chaco'),
        ('Insumos', '28 - Insumos'),
        ('Pago de Premios', '29 - Pago de Premios'),
        ('Comision IPLYC', '30 - Comision IPLYC'),
        ('Ingresos Cap.Fed', '31 - Ingresos Cap.Fed'),
        ('Medicina Prepaga', '32 - Medicina Prepaga'),
        ('Fletes Bs.As', '33 - Fletes Bs.As'),
        ('Fletes Cordoba', '34 - Fletes Cordoba'),
        ('Fletes Corrientes', '35 - Fletes Corrientes'),
        ('Fletes Chaco', '36 - Fletes Chaco'),
        ('Fletes Misiones', '37 - Fletes Misiones'),
        ('Fletes Rio Negro', '38 - Fletes Rio Negro'),
        ('Fletes Santa Fe', '39 - Fletes Santa Fe'),
        ('Fletes Tucuman', '40 - Fletes Tucuman'),
        ('Fletes del Ext.', '41 - Fletes del Ext.'),
        ('Honor.Medicos', '42 - Honor.Medicos'),
        ('Fletes Chubut', '43 - Fletes Chubut'),
        ('Fletes Formosa', '44 - Fletes Formosa'),
        ('Fletes Salta', '45 - Fletes Salta'),
        ('Flete Sgo.Estero', '46 - Flete Sgo.Estero'),
        ('Cpra.DGR Rio Neg', '47 - Cpra.DGR Rio Neg'),
        ('Honorarios Prof.', '48 - Honorarios Prof.')
    ]

choices_TComprobante = [
    ('Ticket', '1 - Ticket'),
    ('Factura', '2 - Factura'),
    ('N.Credito', '3 - N.Credito'),
    ('N.Debito', '4 - N.Debito'),
    ('Recibo', '5 - Recibo'),
    ('Liquidaciones', '6 - Liquidaciones'),
    ('Carta de Porte', '7 - Carta de Porte'),
    ('Sin Comprobantes', '8 - Sin Comprobantes'),
    ('Retencion', '9 - Retencion')
]

choices_Movimiento = [
    ('Sin Comprobantes', '8 - Sin Comprobantes'),
    ('Retencion', '9 - Retencion')
]