# Generated by Django 5.1.4 on 2025-04-20 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opencontability', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='IDCliente',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='IVA',
            field=models.CharField(choices=[('inscripto', 'Inscripto'), ('no_inscripto', 'No Inscripto')], max_length=20),
        ),
        migrations.AlterField(
            model_name='facturas',
            name='Compra_o_Venta',
            field=models.CharField(choices=[('compra', 'Compra'), ('venta', 'Venta')], max_length=6),
        ),
    ]
