# Generated by Django 5.1.4 on 2025-04-20 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opencontability', '0002_alter_clientes_idcliente_alter_clientes_iva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='IVA',
            field=models.CharField(choices=[('Inscripto', 'Inscripto'), ('No inscripto', 'No Inscripto')], max_length=20),
        ),
    ]
