# Generated by Django 5.2.1 on 2025-05-28 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opencontability', '0003_alter_clientes_iva'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='propietario',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='facturas',
            name='propietario',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='facturas',
            name='Importe',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
