# Generated by Django 5.1.4 on 2025-06-02 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opencontability', '0005_alter_clientes_propietario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturas',
            name='Cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opencontability.clientes'),
        ),
        migrations.AlterField(
            model_name='facturas',
            name='Comerciante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='opencontability.clientes'),
        ),
    ]
