# Generated by Django 5.1.7 on 2025-06-03 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opencontability', '0006_alter_facturas_cliente_alter_facturas_comerciante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturas',
            name='CUIT',
        ),
    ]
