# Generated by Django 5.1.6 on 2025-10-02 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opencontability', '0007_remove_facturas_cuit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturas',
            name='Comerciante',
        ),
        migrations.RemoveField(
            model_name='facturas',
            name='Compra_o_Venta',
        ),
        migrations.RemoveField(
            model_name='facturas',
            name='Importe',
        ),
        migrations.RemoveField(
            model_name='facturas',
            name='NComprobante',
        ),
        migrations.AddField(
            model_name='facturas',
            name='Empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='opencontability.clientes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facturas',
            name='Cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='opencontability.clientes'),
        ),
        migrations.AlterField(
            model_name='facturas',
            name='Movimiento',
            field=models.CharField(choices=[('compra', 'Compra'), ('venta', 'Venta')], max_length=6),
        ),
        migrations.AlterField(
            model_name='facturas',
            name='NFactura',
            field=models.CharField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='facturas',
            name='Procesamiento',
            field=models.DateField(auto_now_add=True),
        ),
    ]
